import Head from "next/head";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col justify-center items-center min-h-screen w-full bg-red-800">
          <p className="text-xl text-slate-700">
            Welcome to{" "}
            <span className="text-3xl text-slate-900">Pathsalla</span>
          </p>
          <p>Login as</p>
          <div>
            <Button variant="outline">
              <Link href="/login/teachers">Teacher</Link>
            </Button>
            <Button variant="outline">
              <Link href="/login/students">Student</Link>
            </Button>
          </div>
        </div>
      </main>
    </>
  );
}
